---
title: "README"
author: "Greg Ricci"
date: "April 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting and Cleaning Data Course Project
   Cousera Week 4 Peer Review - TIDY Data Project


## Project Review Criteria:

1.	The submitted data set is tidy. 
2.	The Github repo contains the required scripts.
3.	GitHub contains a code book that modifies and updates the available codebooks with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
4.	The README that explains the analysis files is clear and understandable.
5.	The work submitted for this project is the work of the student who submitted it.


## Project Purpose:

Demonstrate your ability to collect, work with, and clean a data set. The goal is to prepare tidy data that can be used for later analysis. 

Graded by your peers on a series of yes/no questions related to the project.      You will be required to submit: 
      1) a tidy data set as described below, 
      2) a link to a Github repository with your script for performing the analysis, and 
      3) a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data called CodeBook.md. 

You should also include a README.md in the repo with your scripts. This repo explains how all of the scripts work and how they are connected.


## Project Data:

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone

Human Activity Recognition Using Smartphones Data Set
  WEBSITE:[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones]


## Project Data Set Information:

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

## Project Requirments:

Create one R script called run_analysis.R that does the following:
 
 1.	Merges the training and the test sets to create one data set.
 2.	Extracts only the measurements on the mean and standard deviation for each measurement. 
 3.	Uses descriptive activity names to name the activities in the data set
 4.	Appropriately labels the data set with descriptive variable names. 
 5.	From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.


## Project Contents

 1. CodeBook.md - Describes the data and the steps taken to summarize the data.
 2. run_analysis.R - R script to merge, extract, change labels and variables, and summarize the data to a TIDY date form.
 3. run_data_summary.txt - Output file generated by the run_analysis.R script.
 4. README.md - This file.

## The Process:
  a)	Download UCI dataset from web,save on local drive
  b)	Install dplyr package
  c)	Import the dplyr library
  d)	Read txt in the test datasets
       a.	Read in the x test data
       b.	Read in the y test data
       c.	Read in the subject test data
       d. Merge the test datasets into a single dataframe 
  e)	Read txt in the training datasets
     a.	Read in the x training data
     b.	Read in the y training data
     c.	Read in the subject training data
     d. Merge training datasets into a single dataframe 
  f)	Read in the data and identify column names
  g)	Read in the measurement labels dataset 
  h)	merge the datasets into a single dataframe 
  i)	merge the datasets into a single dataframe
  j)	Remove parentheses, hyphens and bad stuff from column names 
  k)	Fix repeating word(s) in columns
  l)	Read activity labels to be added to dataset
  m)	Trim activity labels in datasets
  n)	Group the running data by subject and activity
  o)	Calculate the mean of every measurement 
  p)	Write to text file
  q)	Summaries data / Relax
  


# End - Getting and Cleaning Data Course Project

